[package]
name = "esp32-hal"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>"]
edition = "2018"

[dependencies]
esp32 = { version = "0.2.2" }

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[dev-dependencies]
panic-halt = "0.2.0"
xtensa-lx6-rt = { git = "https://github.com/esp-rs/xtensa-lx6-rt", rev = "e5eb8c4cb893e47172e4e59eadd3d4d9c3093a06" }

[[example]]
name = "blinky"

[profile.dev]
incremental = false

[profile.release]
lto = true
incremental = false
codegen-units = 1
