[package]
name = "esp32-hal"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>", "Arjan Mels <arjan@mels.email>"]
edition = "2018"

[dependencies]
xtensa-lx6-rt = { git = "https://github.com/esp-rs/xtensa-lx6-rt.git", rev = "62229c1" }
esp32 = { version = "0.3.0" }
nb = "0.1.2"
spin = "0.5.2"
embedded-hal = { version = "0.2.3", features = ["unproven"] }

[dev-dependencies]
panic-halt = "0.2.0"
spin = "0.5"

[[example]]
name = "blinky"

[[example]]
name = "serial"

[[example]]
name = "rtccntl"

