[package]
name = "esp32-hal"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>", "Arjan Mels <arjan@mels.email"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

#esp32 = { version = "0.2.2" }
nb = { version = "0.1.2" }

esp32 = { path = "../esp32"}
#esp32 = { version = "0.2.2" }
embedded-hal = {version="0.2.3",features = ["unproven"] }


[profile.dev]
incremental = false
debug = true
codegen-units = 1

[profile.release]
lto = true
incremental = false
debug = true
codegen-units = 1


[dev-dependencies]
xtensa-lx6-rt = { path = "../xtensa-lx6-rt" }
esp32 = { path = "../esp32"}
esp32-hal = { path = "../esp32-hal"}
#esp32-alloc = { path = "../esp32-alloc"}

#corepack = { version = "0.4.0", default-features = false, features = ["alloc"] }
numtoa = "0.2.3"
nb = "0.1.2"
spin = "0.5"

[[example]]
name = "serial"

[[example]]
name = "rtccntl"

[[example]]
name = "adc"
