[package]
name = "esp32-hal"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>", "Arjan Mels <arjan@mels.email>"]
edition = "2018"

[features]
default=["external_ram"]

# Place program completely in ram (needed when e.g. using only ROM bootloader, or for debugging)
all_in_ram=[]

# Allow use of external ram. Needs customized bootloader.
external_ram=["esp32-hal-proc-macros/external_ram"]

# Add support for Global Allocator
alloc=["linked_list_allocator"]

[dependencies]
esp32-hal-proc-macros = { path = "procmacros" }

xtensa-lx6-rt = { git = "https://github.com/esp-rs/xtensa-lx6-rt.git" }
esp32 = { version = "0.3.0" }

nb = "0.1.2"
spin = "0.5.2"
embedded-hal = { version = "0.2.3", features = ["unproven"] }
linked_list_allocator = { version = "0.8.3", optional = true, default-features = false, features = ["alloc_ref"] }

[dev-dependencies]
panic-halt = "0.2.0"

[[example]]
name = "alloc"
required-features = ["alloc"]
