[package]
name = "esp32-hal"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>", "Arjan Mels <arjan@mels.email"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
test=false
bench=false

[dependencies]
xtensa-lx6-rt = { path = "../xtensa-lx6-rt" }
esp32 = { path = "../esp32"}
#esp32 = { version = "0.2.2" }
nb = "0.1.2"
embedded-hal = {version="0.2.3",features = ["unproven"] }

[profile.dev]
incremental = false
debug = true
codegen-units = 1

[profile.release]
lto = true
incremental = false
debug = false
codegen-units = 1

[dev-dependencies]
spin = "0.5"


[[example]]
name = "serial"
#test = false
#bench = false

[[example]]
name = "rtccntl"
#test = false
#bench = false