[package]
name = "esp32-hal"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>", "Arjan Mels <arjan@mels.email"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp32 = { path = "../esp32"}
#esp32 = { version = "0.2.2" }
nb = "0.1.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[profile.dev]
incremental = false
debug = true
codegen-units = 1

[profile.release]
lto = true
incremental = false
debug = true
codegen-units = 1

[dev-dependencies]
xtensa-lx6-rt = { git = "https://github.com/esp-rs/xtensa-lx6-rt", rev = "89cea20c441d4a1624de99c7278df13af5c211a4" }
# esp32 = "0.2.2"
esp32 = { path = "../esp32"}
esp32-hal = { path = "../esp32-hal"}
numtoa = "0.2.3"
nb = "0.1.2"

[[example]]
name = "serial"